backend:
  name: github
  repo: SjrPovoas/serralheriaesoldagens
  branch: main
  base_url: https://api.github.com
  auth_type: pkce
  client_id: 688ac9554755ec3d9df73c36e905a60fc67bd2a2

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "portfolio"
    label: "Portfólio"
    files:
      - file: "portfolio-data.json"
        label: "Lista de Projetos"
        name: "portfolio"
        fields:
          - label: "Projetos"
            name: "projetos"
            widget: "list"
            fields:
              - {label: "Título", name: "title", widget: "string"}
              - {label: "Categoria", name: "categoria", widget: "select", options: ["portoes", "grades", "pergolados", "estruturas"]}
              - {label: "Imagem", name: "image", widget: "image"}